services:
  # Reactフロントエンド
  app:
    build: 
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost:18000
      dockerfile: Dockerfile
    image: gsapp_front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  # Pythonバックエンド
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: gsapp_back
    deploy:
      resources:
        reservations:
          devices:
            # すべてのGPUへのアクセスを許可
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "18000:18000"
    environment:
      - PYTHONPATH=/app
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
